# Create the environment:
# mamba env create -f environment-dev.yml 
# or if you really want to use conda
# conda env create -f environment-dev.yml

name: aqua-dev
channels:
  - conda-forge
  - nodefaults
# please note that some of these dependencies are made explicit on purpose, but are not directly required by conda/mamba
dependencies:
  - python>=3.10,<3.13
  - cdo>=2.5.0 #for smmregrid compatibility
  - eccodes==2.41.0
  # for eccodes see issues #252, #634, #870, #1282
  # PR #36 catalog repo
  - cartopy_offlinedata # this is needed for MN5 HPC
  - pandas      
  - pip
  - hdf5 #explicitly to avoid issues with pypi version
  - tempest-extremes # for TCs
  - xesmf # for ECmean
  - imagemagick
  - healpy
  - pip:
    - -e ../AQUA
    - -e ./frontier-diagnostics/tropical_cyclones/ # pip install -e of tropical cyclones
    - -e ./frontier-diagnostics/tropical_rainfall/ # pip install -e of tropical_rainfall
    # pip install -e of AQUA itself
    - -e .[dev]
