name: "AQUA-diagnostics container build and publish"

on:
  release:
    types: [published]
  workflow_dispatch:
  # push: # We remove this to create the container only when we create a release from browser (issue #490)
  #   tags:
  #     - v*

env:
  IMAGE_NAME: aqua-diagnostics
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       packages: write
       contents: read
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: Set build arguments based on tag
        id: set_build_args
        run: echo "BUILD_ARGS=--build-arg EXTRA_PACKAGES=cartopy_offlinedata" >> $GITHUB_ENV
      - name: "Log in to registry"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }}  --password-stdin
      - name: "build container"
        run: docker build $BUILD_ARGS --file dockerfiles/Dockerfile.aqua-diagnostics --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" .
      - name: "publish container"
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Extract tag or branch name (e.g., refs/tags/v0.19.0+op â†’ v0.19.0+op)
          RAW_REF="${{ github.ref_name }}"

          # Remove leading 'v' if present and replace '+' with '-' for Docker tag compatibility
          VERSION=$(echo "$RAW_REF" | sed -e 's/^v//' -e 's/+/-/g')
          
           # Handle main branch special case
          [ "$VERSION" == "main" ] && VERSION=latest

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"

          docker tag "$IMAGE_NAME" "$IMAGE_ID:$VERSION"
          docker push "$IMAGE_ID:$VERSION"